2020-05-16 10:40:52,200 ERROR: Exception on /favicon.ico [GET] [in D:\flasktest\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "D:\flasktest\venv\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "D:\flasktest\venv\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "D:\flasktest\app\errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "D:\flasktest\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "D:\flasktest\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\flasktest\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\flasktest\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\flasktest\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\flasktest\app\templates\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\flasktest\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 6, in block "html"
    {%- block head %}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 7, in block "head"
    <title>{% block title %}{{title|default}}{% endblock title %}</title>
  File "D:\flasktest\app\templates\base.html", line 4, in block "title"
    {% if title %}{{ title }} - Microblog{% else %}{{ _('Welcome to Microblog') }}{% endif %}
jinja2.exceptions.UndefinedError: '_' is undefined
2020-05-16 13:01:10,119 INFO: Microblog startup [in D:\flasktest\app\__init__.py:57]
2020-05-16 13:01:39,062 ERROR: Exception on /explore [GET] [in D:\flasktest\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\flasktest\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\flasktest\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flasktest\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\flasktest\app\routes.py", line 167, in explore
    next_url=next_url, prev_url=prev_url)
  File "D:\flasktest\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "D:\flasktest\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\flasktest\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\flasktest\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\flasktest\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\flasktest\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\flasktest\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\flasktest\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "D:\flasktest\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "D:\flasktest\app\templates\_post.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\flasktest\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\flasktest\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "D:\flasktest\app\templates\_post.html", line 8, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "D:\flasktest\venv\lib\site-packages\jinja2\runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "D:\flasktest\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 200, in template
    {{ form.hidden_tag() }}
  File "D:\flasktest\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-16 13:03:48,041 INFO: Microblog startup [in D:\flasktest\app\__init__.py:57]
